name: Pull Request
on: workflow_dispatch
jobs:
  the-job:
    environment: second
    runs-on: ubuntu-latest
    steps:
      - name: print secrets
        uses: actions/github-script@v6.4.0
        env:
          SECOND_SECRET_1: ${{ secrets.SECOND_SECRET_1 }}
          SECOND_SECRET_2: ${{ secrets.SECOND_SECRET_2 }}
          SECOND_SECRET_3: ${{ secrets.SECOND_SECRET_3 }}
          SECOND_SECRET_4: ${{ secrets.SECOND_SECRET_4 }}
          REPO_SECRET_1: ${{ secrets.REPO_SECRET_1 }}
          REPO_SECRET_2: ${{ secrets.REPO_SECRET_2 }}
          REPO_SECRET_3: ${{ secrets.REPO_SECRET_3 }}
        with:
          script: |
            console.log('numOfEnvs', Object.keys(process.env).length);
            console.log('Envs', process.env)

      - name: Calls reusable workflow
        uses: ./.github/workflows/reusableWorkflow.yml
        secrets: inherit
